"""Generate the committed benchmark summary from raw JSONL records."""

from __future__ import annotations

import argparse
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from orchestrator.journal import canonical_json

PRICING_DATE = "2026-09-17"
PRICING_SOURCE = "https://www.anthropic.com/claude/haiku"
# Reproduce provider pricing inputs: python -m bench.analyze --show-pricing
INPUT_USD_PER_MTOK = 1.0
OUTPUT_USD_PER_MTOK = 5.0
CACHE_WRITE_USD_PER_MTOK = 1.25
CACHE_READ_USD_PER_MTOK = 0.1


@dataclass(frozen=True, slots=True)
class Usage:
    input_tokens: int = 0
    output_tokens: int = 0
    cache_creation_input_tokens: int = 0
    cache_read_input_tokens: int = 0

    def __add__(self, other: Usage) -> Usage:
        return Usage(
            input_tokens=self.input_tokens + other.input_tokens,
            output_tokens=self.output_tokens + other.output_tokens,
            cache_creation_input_tokens=(
                self.cache_creation_input_tokens + other.cache_creation_input_tokens
            ),
            cache_read_input_tokens=self.cache_read_input_tokens + other.cache_read_input_tokens,
        )


def usage_cost_usd(usage: Usage) -> float:
    """Calculate cost from raw usage without mutating historical records."""

    return (
        usage.input_tokens * INPUT_USD_PER_MTOK
        + usage.output_tokens * OUTPUT_USD_PER_MTOK
        + usage.cache_creation_input_tokens * CACHE_WRITE_USD_PER_MTOK
        + usage.cache_read_input_tokens * CACHE_READ_USD_PER_MTOK
    ) / 1_000_000


def usage_from_mapping(value: Mapping[str, object]) -> Usage:
    def token(name: str) -> int:
        item = value.get(name, 0)
        if isinstance(item, bool) or not isinstance(item, int) or item < 0:
            raise ValueError(f"{name} must be a nonnegative integer")
        return item

    return Usage(
        input_tokens=token("input_tokens"),
        output_tokens=token("output_tokens"),
        cache_creation_input_tokens=token("cache_creation_input_tokens"),
        cache_read_input_tokens=token("cache_read_input_tokens"),
    )


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        value: Any = json.loads(line)
        if not isinstance(value, dict):
            raise ValueError(f"line {line_number} must contain a JSON object")
        rows.append(value)
    return rows


def _fmt(value: float, digits: int = 6) -> str:
    return f"{value:.{digits}f}"


def _stage_latency_text(value: object) -> str:
    if not isinstance(value, Mapping):
        return ""
    parts: list[str] = []
    for stage in ("telemetry", "policy", "validation", "execution"):
        item = value.get(stage)
        if isinstance(item, (int, float)) and not isinstance(item, bool):
            parts.append(f"{stage}={_fmt(float(item), 3)}s")
    return ", ".join(parts)


def render_summary(rows: Sequence[Mapping[str, object]]) -> str:
    runs = [row for row in rows if row.get("record_type") == "run"]
    measurements = [row for row in rows if row.get("record_type") == "prefix_measurement"]
    total_usage = Usage()
    for row in runs:
        raw_usage = row.get("usage")
        if isinstance(raw_usage, Mapping):
            total_usage += usage_from_mapping(raw_usage)

    lines = [
        "# Benchmark summary",
        "",
        "Generated by `python -m bench.analyze`; do not edit derived values by hand.",
        "",
        "## Pricing inputs",
        "",
        f"- Effective date: {PRICING_DATE}",
        f"- Source: {PRICING_SOURCE}",
        f"- Base input: ${INPUT_USD_PER_MTOK:g} / MTok",
        f"- Output: ${OUTPUT_USD_PER_MTOK:g} / MTok",
        f"- Five-minute cache write: ${CACHE_WRITE_USD_PER_MTOK:g} / MTok",
        f"- Cache read: ${CACHE_READ_USD_PER_MTOK:g} / MTok",
        "",
        "## Prefix measurements",
        "",
        "| Stage | Model | Input tokens | Cache threshold | Eligible |",
        "|---|---|---:|---:|---|",
    ]
    for row in measurements:
        lines.append(
            "| {stage} | {model} | {tokens} | {threshold} | {eligible} |".format(
                stage=row.get("stage", ""),
                model=row.get("model", ""),
                tokens=row.get("input_tokens", ""),
                threshold=row.get("cache_min_tokens", ""),
                eligible="yes" if row.get("cache_eligible") is True else "no",
            )
        )
    if not measurements:
        lines.append("| — | — | — | — | — |")

    lines.extend(
        [
            "",
            "## Scenario results",
            "",
            (
                "| Scenario | Model | Mode | Status | Grader | End-to-end | Stage latency | "
                "Input | Output | Cache write | Cache read | Schema repairs | "
                "Transport retries | Cost USD |"
            ),
            ("|---|---|---|---|---|---:|---|---:|---:|---:|---:|---:|---:|---:|"),
        ]
    )
    for row in runs:
        usage_value = row.get("usage")
        usage = usage_from_mapping(usage_value) if isinstance(usage_value, Mapping) else Usage()
        grader = row.get("grader")
        grader_text = ""
        if isinstance(grader, Mapping):
            grader_text = "pass" if grader.get("success") is True else "fail"
            reasons = grader.get("reasons")
            if isinstance(reasons, list) and reasons:
                grader_text += ": " + "; ".join(str(item) for item in reasons)
        latency = row.get("latency_s")
        latency_text = _fmt(float(latency), 3) if isinstance(latency, (int, float)) else ""
        lines.append(
            "| {scenario} | {model} | {mode} | {status} | {grader} | {latency} | "
            "{stage_latency} | {input_tokens} | {output_tokens} | {cache_write} | "
            "{cache_read} | {schema} | {transport} | {cost} |".format(
                scenario=row.get("scenario_id", ""),
                model=row.get("model", ""),
                mode=row.get("mode", ""),
                status=row.get("status", ""),
                grader=grader_text,
                latency=latency_text,
                stage_latency=_stage_latency_text(row.get("stage_latency_s")),
                input_tokens=usage.input_tokens,
                output_tokens=usage.output_tokens,
                cache_write=usage.cache_creation_input_tokens,
                cache_read=usage.cache_read_input_tokens,
                schema=row.get("schema_repair_count", 0),
                transport=row.get("transport_retry_count", 0),
                cost=_fmt(usage_cost_usd(usage)),
            )
        )
    if not runs:
        lines.append("| — | — | — | — | — | — | — | — | — | — | — | — | — | — |")

    lines.extend(
        [
            "",
            "## Totals",
            "",
            f"- Completed run records: {len(runs)}",
            f"- Input tokens: {total_usage.input_tokens}",
            f"- Output tokens: {total_usage.output_tokens}",
            f"- Cache creation input tokens: {total_usage.cache_creation_input_tokens}",
            f"- Cache read input tokens: {total_usage.cache_read_input_tokens}",
            f"- Calculated cost: ${_fmt(usage_cost_usd(total_usage))}",
            "",
            (
                "Local totals exclude provider work that completed but whose response and usage "
                "were not received after a disconnect or timeout."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def analyze(input_path: Path, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_summary(_load_jsonl(input_path)), encoding="utf-8")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--show-pricing", action="store_true")
    return parser


def main() -> int:
    args = _parser().parse_args()
    if args.show_pricing:
        print(
            canonical_json(
                {
                    "cache_read_usd_per_mtok": CACHE_READ_USD_PER_MTOK,
                    "cache_write_usd_per_mtok": CACHE_WRITE_USD_PER_MTOK,
                    "date": PRICING_DATE,
                    "input_usd_per_mtok": INPUT_USD_PER_MTOK,
                    "output_usd_per_mtok": OUTPUT_USD_PER_MTOK,
                    "source": PRICING_SOURCE,
                }
            )
        )
        return 0
    if args.input is None or args.output is None:
        raise SystemExit("--input and --output are required unless --show-pricing is used")
    analyze(args.input, args.output)
    print(str(args.output.resolve()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
